#spring:
#  application:
#    name: USERPROFILE-SERVICE
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: UserProfileService
#
#
##  kafka:
##    bootstrap-servers: kafka:9092
##  producer:
##    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
##    key-serializer: org.apache.kafka.common.serialization.StringSerializer
#
##  config:
##    import: optional:configserver:http://localhost:8085
#
#server:
#  port: 8081
#
#jwt:
#  secret: secret
#
#app:
#  jwttoken:
#    message: Login Successful
#  controller:
#    exception:
#      message1: Id and Password Empty
#      message2: Id and Password not found
#      message3: Id and Password invalid
#  service:
#    message1: User Already Exists
#    message2: Invalid Id and Password
#
#
##auth:
##  service:
##    url: http://localhost:8080/api/v1
#
#  mail:
#    host: smtp.office365.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
